import argparse
from pathlib import Path

from .common import print_jsonl


def _project_pipeline_entries_toml(*, include_custom_pipeline: bool) -> list[str]:
    entries = []
    if include_custom_pipeline:
        entries.append('  { class = "pipelines.CleanBookPipeline" },')
    entries.append('  { type = "jsonl", path = "output.jsonl" },')
    return entries


def project_config_toml(
    project_name: str, *, include_custom_pipeline: bool = False
) -> str:
    pipeline_entries = "\n".join(
        _project_pipeline_entries_toml(include_custom_pipeline=include_custom_pipeline)
    )
    return f'''name = "{project_name}"
user_agent = "webuse/{project_name}"
robots_txt = false

[llm]
# model = "gpt-4.1-mini"
# api_key = "sk-..."
# base_url = "https://api.openai.com/v1"

[concurrency]
limit = 5
per_domain = 1

[items.pipelines]
default = [
{pipeline_entries}
]

[log]
level = "info"
file = "stderr"
append = true
'''


def project_config_yaml(
    project_name: str, *, include_custom_pipeline: bool = False
) -> str:
    custom_pipeline = (
        "      - class: pipelines.CleanBookPipeline\n"
        if include_custom_pipeline
        else ""
    )
    return f"""name: {project_name}
user_agent: webuse/{project_name}
robots_txt: false
llm: {{}}
# llm:
#   model: gpt-4.1-mini
#   api_key: sk-...
#   base_url: https://api.openai.com/v1
concurrency:
  limit: 5
  per_domain: 1
items:
  pipelines:
    default:
{custom_pipeline}      - type: jsonl
        path: output.jsonl
log:
  level: info
  file: stderr
  append: true
"""


def _project_template(project_name: str, *, package_name: str) -> dict[str, str]:
    run_command = (
        f"cd ..\nwebuse crawl {package_name} --spider books -o books.jsonl"
        if package_name.isidentifier()
        else "webuse crawl --spider books -o books.jsonl"
    )
    return {
        "README.md": f"""# {project_name}

Generated by `webuse create`.

## Generate a Spider

```bash
webuse gen books https://books.toscrape.com/ --directory .
{run_command}
```

## Fetch

```bash
webuse fetch https://books.toscrape.com/ --css "article.product_pod h3 a" --attr title --all
```

## Items

`items.py` contains Pydantic models for scraped records.
`pipelines.py` contains item cleanup and storage hooks.
""",
        ".gitignore": """selectors.json
output.jsonl
*.sqlite
*.sqlite-*
""",
        "__init__.py": "",
        "spiders/__init__.py": "",
        "webuse.toml": project_config_toml(project_name, include_custom_pipeline=True),
        "items.py": """from pydantic import BaseModel, Field


class BookItem(BaseModel):
    title: str
    price: str = ""
    availability: str = Field(default="", description="Raw availability text from the listing page.")


__all__ = ["BookItem"]
""",
        "pipelines.py": """import webuse
from pydantic import BaseModel


class CleanBookPipeline(webuse.Pipeline):
    def process_item(self, item: BaseModel):
        return item


__all__ = ["CleanBookPipeline"]
""",
    }


def create_command(args: argparse.Namespace) -> int:
    target = Path(args.directory)
    project_name = args.name or target.name

    if target.exists() and not target.is_dir():
        raise SystemExit(f"create target exists and is not a directory: {target}")
    if target.exists() and any(target.iterdir()) and not args.force:
        raise SystemExit(
            f"create target is not empty: {target}. Use --force to write scaffold files anyway."
        )

    target.mkdir(parents=True, exist_ok=True)
    (target / ".webuse").mkdir(exist_ok=True)
    (target / "spiders").mkdir(exist_ok=True)

    written: list[str] = []
    for relative_path, content in _project_template(
        project_name, package_name=target.name
    ).items():
        path = target / relative_path
        if path.exists() and not args.force:
            raise SystemExit(f"refusing to overwrite existing file: {path}")
        path.write_text(content, encoding="utf-8")
        written.append(relative_path)

    print_jsonl(
        [
            {
                "path": str(target),
                "project": project_name,
                "files": written,
            }
        ]
    )
    return 0


def register(subparsers: argparse._SubParsersAction) -> None:
    create_parser = subparsers.add_parser("create")
    create_parser.add_argument("directory")
    create_parser.add_argument("--name")
    create_parser.add_argument("--force", action="store_true")
    create_parser.set_defaults(func=create_command)
